// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID              pgtype.UUID      `json:"id"`
	InboxID         string           `json:"inbox_id"`
	Kind            string           `json:"kind"`
	Header          string           `json:"header"`
	Ciphertext      string           `json:"ciphertext"`
	UsedPrekeyID    pgtype.UUID      `json:"used_prekey_id"`
	ClientMessageID string           `json:"client_message_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	ExpiresAt       pgtype.Timestamp `json:"expires_at"`
}

type OneTimePrekey struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Prekey    string           `json:"prekey"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID                    pgtype.UUID      `json:"id"`
	Username              string           `json:"username"`
	IdentityKey           string           `json:"identity_key"`
	SignedPrekey          string           `json:"signed_prekey"`
	SignedPrekeySignature string           `json:"signed_prekey_signature"`
	InboxID               string           `json:"inbox_id"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
}
