// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one

INSERT INTO messages (inbox_id, kind, header, ciphertext, used_prekey_id, client_message_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, expires_at
`

type CreateMessageParams struct {
	InboxID         string      `json:"inbox_id"`
	Kind            string      `json:"kind"`
	Header          string      `json:"header"`
	Ciphertext      string      `json:"ciphertext"`
	UsedPrekeyID    pgtype.UUID `json:"used_prekey_id"`
	ClientMessageID string      `json:"client_message_id"`
}

type CreateMessageRow struct {
	ID        pgtype.UUID      `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

// ============ MESSAGES ============
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.InboxID,
		arg.Kind,
		arg.Header,
		arg.Ciphertext,
		arg.UsedPrekeyID,
		arg.ClientMessageID,
	)
	var i CreateMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const createPrekey = `-- name: CreatePrekey :one

INSERT INTO one_time_prekeys (user_id, prekey)
VALUES ($1, $2)
RETURNING id
`

type CreatePrekeyParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Prekey string      `json:"prekey"`
}

// ============ ONE-TIME PREKEYS ============
func (q *Queries) CreatePrekey(ctx context.Context, arg CreatePrekeyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPrekey, arg.UserID, arg.Prekey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, identity_key, signed_prekey, signed_prekey_signature, inbox_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, inbox_id, created_at
`

type CreateUserParams struct {
	Username              string `json:"username"`
	IdentityKey           string `json:"identity_key"`
	SignedPrekey          string `json:"signed_prekey"`
	SignedPrekeySignature string `json:"signed_prekey_signature"`
	InboxID               string `json:"inbox_id"`
}

type CreateUserRow struct {
	ID        pgtype.UUID      `json:"id"`
	Username  string           `json:"username"`
	InboxID   string           `json:"inbox_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// ============ USERS ============
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.IdentityKey,
		arg.SignedPrekey,
		arg.SignedPrekeySignature,
		arg.InboxID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.InboxID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredMessages = `-- name: DeleteExpiredMessages :execrows
DELETE FROM messages
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredMessages(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMessages)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMessagesByInboxID = `-- name: GetMessagesByInboxID :many
SELECT id, inbox_id, kind, header, ciphertext, used_prekey_id, client_message_id, created_at, expires_at
FROM messages
WHERE inbox_id = $1
  AND expires_at > NOW()
ORDER BY created_at ASC
LIMIT $2
`

type GetMessagesByInboxIDParams struct {
	InboxID string `json:"inbox_id"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) GetMessagesByInboxID(ctx context.Context, arg GetMessagesByInboxIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByInboxID, arg.InboxID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.InboxID,
			&i.Kind,
			&i.Header,
			&i.Ciphertext,
			&i.UsedPrekeyID,
			&i.ClientMessageID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrekeyByUsername = `-- name: GetPrekeyByUsername :one
SELECT p.id, p.user_id, p.prekey, p.created_at
FROM one_time_prekeys p
INNER JOIN users u ON u.id = p.user_id
WHERE u.username = $1
ORDER BY p.created_at ASC
LIMIT 1
`

func (q *Queries) GetPrekeyByUsername(ctx context.Context, username string) (OneTimePrekey, error) {
	row := q.db.QueryRow(ctx, getPrekeyByUsername, username)
	var i OneTimePrekey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Prekey,
		&i.CreatedAt,
	)
	return i, err
}

const getPrekeysCountByUsername = `-- name: GetPrekeysCountByUsername :one
SELECT COUNT(*) AS count
FROM one_time_prekeys p
INNER JOIN users u ON u.id = p.user_id
WHERE u.username = $1
`

func (q *Queries) GetPrekeysCountByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, getPrekeysCountByUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByInboxID = `-- name: GetUserByInboxID :one
SELECT id, username, identity_key, signed_prekey, signed_prekey_signature, inbox_id, created_at
FROM users
WHERE inbox_id = $1
`

func (q *Queries) GetUserByInboxID(ctx context.Context, inboxID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByInboxID, inboxID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IdentityKey,
		&i.SignedPrekey,
		&i.SignedPrekeySignature,
		&i.InboxID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, identity_key, signed_prekey, signed_prekey_signature, inbox_id, created_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IdentityKey,
		&i.SignedPrekey,
		&i.SignedPrekeySignature,
		&i.InboxID,
		&i.CreatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1) AS exists
`

func (q *Queries) UserExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
