// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT public_key, name FROM Users
WHERE public_key = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, publicKey string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, publicKey)
	var i User
	err := row.Scan(&i.PublicKey, &i.Name)
	return i, err
}
